version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ECR_REPO>
      - REPOSITORY_URI=<ECR_REPO>
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building JAR...
      - mvn clean install -DskipTests
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating Dockerrun.aws.json...
      - >
        echo "{ \"AWSEBDockerrunVersion\": 1, \"Image\": { \"Name\": \"$REPOSITORY_URI:$IMAGE_TAG\", \"Update\": \"true\" }, \"Ports\": [{ \"ContainerPort\": 5000 }] }" > Dockerrun.aws.json

artifacts:
  files:
    - Dockerrun.aws.json
