version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn install -DskipTests=true
  build:
    commands:
      - echo Building the application...
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo Build completed on `date`
      - ls target/
      - cp target/Final-0.0.1-SNAPSHOT.jar application.jar
artifacts:
  files:
    - application.jar
